modLoader = "javafml"
loaderVersion = "[36,)"
license = "All rights reserved."

[[mods]]
modId = "example"
version = "${file.jarVersion}"
displayName = "Example"
authors = "Peyang"
description = "Example mod."
